spring:
  application:
    name: Chirp10

  profiles:
    active: dev

  data:
    redis:
      host: "redis-10457.c281.us-east-1-2.ec2.cloud.redislabs.com"
      password: ${REDIS_PASSWORD}
      username: "default"
      port: 10457
#      connect-timeout: 5000ms
      connect-timeout: 19000ms
      timeout: 9000ms
#      timeout: 2000ms


  datasource:
    url: jdbc:postgresql://db.ofsbfhjptlzjdkwcgaxe.supabase.co:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 12000000
      validation-timeout: 5000
      pool-name: SpringBootHikariCP
      data-source-properties:
        prepareThreshold: 5
        preparedStatementCacheQueries: 256
        preparedStatementCacheSizeMib: 5
        tcpKeepAlive: true
        socketTimeOut: 30
        connectTimeOut: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
        show-sql: true

  mail:
    port: 587
    password: ${MAILGUN_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  rabbitmq:
    host: seal.lmq.cloudamqp.com
    password: ${RABBITMQ_PASSWORD}
    username: uazqhplv
    ssl:
      enabled: true
    virtual-host: uazqhplv
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 3
        prefetch: 10
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 1000ms
          max-interval: 10000ms
          max-attempts: 3
          multiplier: 2

jwt:
  secret: ${JWT_SECRET_BASE64}

chirp10:
  email:
    from: mail@melatech.com
    verification:
      expiry-hours: 24
    reset-password:
      expiry-minutes: 30

nginx:
  trusted-ips:
    - "127.0.0.1" # nginx on same machine
    - "::1" # IPv6 localhost
    - "172.17.0.0/16" # nginx container IP when using Docker
    - "10.0.0.5/32" # nginx server IP (if separate machine)

supabase:
  url: "https://ofsbfhjptlzjdkwcgaxe.supabase.co"
  service-key: ${SUPABASE_SERVICE_KEY}

firebase:
  credentials-path: "classpath:firebase-credentials/chirp10-firebase-adminsdk1.json"

