spring:
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.mailgun.org
    username: bridgehouseexchange1!@sandbox41029d0bc4d642f48df8161e4b271dd7.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

chirp10:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: true
  web-socket:
    allowed-origin: "http://localhost:8080"

logging:
  level:
    com.melatech.chirp10: DEBUG